import React, { useState, useCallback, useRef } from "react";
import { useDropzone } from "react-dropzone";
import { 
  FileText, 
  Image as ImageIcon, 
  Globe, 
  FileCode, 
  Settings, 
  Download, 
  Plus, 
  Trash2, 
  Loader2, 
  ChevronRight,
  Layout,
  Type,
  Maximize2,
  FileDown,
  Sparkles,
  Eye
} from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import * as mammoth from "mammoth";
import * as XLSX from "xlsx";
import ReactMarkdown from "react-markdown";

import { generatePDF, type PDFOptions } from "./services/pdfService";
import { extractTextFromImage, formatContentForPDF, fetchContentFromUrl } from "./services/geminiService";

function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

interface ContentItem {
  id: string;
  type: "text" | "image" | "markdown" | "url" | "doc";
  name: string;
  data: string;
  originalFile?: File;
  aiProcessing?: boolean;
}

export default function App() {
  const [items, setItems] = useState<ContentItem[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isProcessingAI, setIsProcessingAI] = useState(false);
  const [showPreview, setShowPreview] = useState(false);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [showUrlModal, setShowUrlModal] = useState(false);
  const [urlInput, setUrlInput] = useState("");
  const [isFetchingUrl, setIsFetchingUrl] = useState(false);

  const addUrlContent = async () => {
    if (!urlInput) return;
    setIsFetchingUrl(true);
    try {
      // Using Gemini to "fetch" and summarize the URL since we can't easily fetch cross-origin
      const response = await fetchContentFromUrl(urlInput);
      const id = Math.random().toString(36).substring(7);
      setItems(prev => [...prev, { id, type: "markdown", name: `Web: ${urlInput}`, data: response }]);
      setShowUrlModal(false);
      setUrlInput("");
    } catch (error) {
      console.error("URL fetch failed", error);
    } finally {
      setIsFetchingUrl(false);
    }
  };
  
  const [options, setOptions] = useState<PDFOptions>({
    pageSize: "a4",
    orientation: "p",
    title: "My Document",
    author: "",
    header: "",
    footer: "Generated by All Things to PDF",
    showPageNumbers: true,
    includeTOC: false,
  });

  const onDrop = useCallback(async (acceptedFiles: File[]) => {
    for (const file of acceptedFiles) {
      const id = Math.random().toString(36).substring(7);
      const name = file.name;
      const extension = name.split(".").pop()?.toLowerCase();

      if (["jpg", "jpeg", "png", "webp"].includes(extension || "")) {
        const reader = new FileReader();
        reader.onload = (e) => {
          setItems(prev => [...prev, { id, type: "image", name, data: e.target?.result as string, originalFile: file }]);
        };
        reader.readAsDataURL(file);
      } else if (["txt", "md", "json"].includes(extension || "")) {
        const text = await file.text();
        setItems(prev => [...prev, { id, type: extension === "md" ? "markdown" : "text", name, data: text, originalFile: file }]);
      } else if (extension === "docx") {
        const arrayBuffer = await file.arrayBuffer();
        const result = await mammoth.extractRawText({ arrayBuffer });
        setItems(prev => [...prev, { id, type: "text", name, data: result.value, originalFile: file }]);
      } else if (["xlsx", "xls"].includes(extension || "")) {
        const arrayBuffer = await file.arrayBuffer();
        const workbook = XLSX.read(arrayBuffer);
        const firstSheet = workbook.Sheets[workbook.SheetNames[0]];
        const csv = XLSX.utils.sheet_to_csv(firstSheet);
        setItems(prev => [...prev, { id, type: "text", name, data: csv, originalFile: file }]);
      }
    }
  }, []);

  const { getRootProps, getInputProps, isDragActive } = useDropzone({ onDrop });

  const removeItem = (id: string) => {
    setItems(prev => prev.filter(item => item.id !== id));
  };

  const handleAIProcess = async (id: string) => {
    const item = items.find(i => i.id === id);
    if (!item) return;

    setIsProcessingAI(true);
    setItems(prev => prev.map(i => i.id === id ? { ...i, aiProcessing: true } : i));

    try {
      if (item.type === "image") {
        const text = await extractTextFromImage(item.data);
        setItems(prev => prev.map(i => i.id === id ? { ...i, type: "text", data: text, aiProcessing: false } : i));
      } else {
        const formatted = await formatContentForPDF(item.data, { title: options.title, includeTOC: options.includeTOC });
        setItems(prev => prev.map(i => i.id === id ? { ...i, type: "markdown", data: formatted, aiProcessing: false } : i));
      }
    } catch (error) {
      console.error("AI Processing failed", error);
      setItems(prev => prev.map(i => i.id === id ? { ...i, aiProcessing: false } : i));
    } finally {
      setIsProcessingAI(false);
    }
  };

  const handleGeneratePDF = async () => {
    if (items.length === 0) return;
    setIsGenerating(true);
    try {
      const blob = await generatePDF(items.map(i => ({ type: i.type as any, data: i.data })), options);
      const url = URL.createObjectURL(blob);
      setPreviewUrl(url);
      setShowPreview(true);
    } catch (error) {
      console.error("PDF generation failed", error);
    } finally {
      setIsGenerating(false);
    }
  };

  const downloadPDF = () => {
    if (!previewUrl) return;
    const link = document.createElement("a");
    link.href = previewUrl;
    link.download = `${options.title || "document"}.pdf`;
    link.click();
  };

  return (
    <div className="min-h-screen bg-[#F5F5F7] text-[#1D1D1F] font-sans selection:bg-blue-100">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-white/80 backdrop-blur-md border-b border-gray-200 px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-blue-600 rounded-xl flex items-center justify-center shadow-lg shadow-blue-200">
            <FileDown className="text-white w-6 h-6" />
          </div>
          <div>
            <h1 className="text-lg font-semibold tracking-tight">All Things to PDF</h1>
            <p className="text-xs text-gray-500 font-medium">AI-Powered Universal Converter</p>
          </div>
        </div>
        
        <div className="flex items-center gap-4">
          <button 
            onClick={() => setShowUrlModal(true)}
            className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-600 hover:bg-gray-100 rounded-full transition-colors"
          >
            <Globe className="w-4 h-4" />
            Add URL
          </button>
          <button 
            onClick={handleGeneratePDF}
            disabled={items.length === 0 || isGenerating}
            className={cn(
              "flex items-center gap-2 px-5 py-2.5 rounded-full font-medium transition-all",
              items.length > 0 
                ? "bg-blue-600 text-white hover:bg-blue-700 shadow-md hover:shadow-lg active:scale-95" 
                : "bg-gray-100 text-gray-400 cursor-not-allowed"
            )}
          >
            {isGenerating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
            Generate PDF
          </button>
        </div>
      </header>

      <main className="max-w-7xl mx-auto p-6 grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Sidebar Options */}
        <aside className="lg:col-span-4 space-y-6">
          <div className="bg-white rounded-3xl p-6 shadow-sm border border-gray-100 space-y-6">
            <div className="flex items-center gap-2 pb-2 border-b border-gray-50">
              <Settings className="w-4 h-4 text-blue-600" />
              <h2 className="font-semibold text-sm uppercase tracking-wider text-gray-500">Document Settings</h2>
            </div>

            <div className="space-y-4">
              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-gray-500 uppercase ml-1">Document Title</label>
                <input 
                  type="text" 
                  value={options.title}
                  onChange={(e) => setOptions({...options, title: e.target.value})}
                  className="w-full px-4 py-3 bg-gray-50 border-none rounded-2xl focus:ring-2 focus:ring-blue-500 transition-all outline-none"
                  placeholder="Enter title..."
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <label className="text-xs font-semibold text-gray-500 uppercase ml-1">Page Size</label>
                  <select 
                    value={options.pageSize}
                    onChange={(e) => setOptions({...options, pageSize: e.target.value as any})}
                    className="w-full px-4 py-3 bg-gray-50 border-none rounded-2xl focus:ring-2 focus:ring-blue-500 outline-none appearance-none"
                  >
                    <option value="a4">A4</option>
                    <option value="letter">Letter</option>
                    <option value="legal">Legal</option>
                  </select>
                </div>
                <div className="space-y-1.5">
                  <label className="text-xs font-semibold text-gray-500 uppercase ml-1">Orientation</label>
                  <select 
                    value={options.orientation}
                    onChange={(e) => setOptions({...options, orientation: e.target.value as any})}
                    className="w-full px-4 py-3 bg-gray-50 border-none rounded-2xl focus:ring-2 focus:ring-blue-500 outline-none appearance-none"
                  >
                    <option value="p">Portrait</option>
                    <option value="l">Landscape</option>
                  </select>
                </div>
              </div>

              <div className="space-y-3 pt-2">
                <label className="flex items-center gap-3 cursor-pointer group">
                  <input 
                    type="checkbox" 
                    checked={options.showPageNumbers}
                    onChange={(e) => setOptions({...options, showPageNumbers: e.target.checked})}
                    className="w-5 h-5 rounded-lg border-gray-300 text-blue-600 focus:ring-blue-500"
                  />
                  <span className="text-sm font-medium text-gray-700 group-hover:text-gray-900 transition-colors">Show Page Numbers</span>
                </label>
                <label className="flex items-center gap-3 cursor-pointer group">
                  <input 
                    type="checkbox" 
                    checked={options.includeTOC}
                    onChange={(e) => setOptions({...options, includeTOC: e.target.checked})}
                    className="w-5 h-5 rounded-lg border-gray-300 text-blue-600 focus:ring-blue-500"
                  />
                  <span className="text-sm font-medium text-gray-700 group-hover:text-gray-900 transition-colors">Include Table of Contents</span>
                </label>
              </div>
            </div>
          </div>

          <div className="bg-blue-50 rounded-3xl p-6 border border-blue-100">
            <div className="flex items-center gap-2 mb-3">
              <Sparkles className="w-4 h-4 text-blue-600" />
              <h3 className="font-semibold text-blue-900">AI Features</h3>
            </div>
            <p className="text-sm text-blue-800/70 leading-relaxed">
              Use Gemini AI to extract text from images (OCR) or reformat your content into professional markdown before generating the PDF.
            </p>
          </div>
        </aside>

        {/* Main Content */}
        <div className="lg:col-span-8 space-y-6">
          {/* Dropzone */}
          <div 
            {...getRootProps()} 
            className={cn(
              "relative border-2 border-dashed rounded-[2rem] p-12 transition-all cursor-pointer flex flex-col items-center justify-center gap-4",
              isDragActive ? "border-blue-500 bg-blue-50/50" : "border-gray-200 bg-white hover:border-blue-400 hover:bg-gray-50/50"
            )}
          >
            <input {...getInputProps()} />
            <div className="w-16 h-16 bg-gray-50 rounded-2xl flex items-center justify-center text-gray-400 group-hover:text-blue-500 transition-colors">
              <Plus className="w-8 h-8" />
            </div>
            <div className="text-center">
              <p className="text-lg font-semibold text-gray-900">Click or drag files here</p>
              <p className="text-sm text-gray-500 mt-1">Images, DOCX, XLSX, TXT, MD, JSON</p>
            </div>
          </div>

          {/* Content List */}
          <div className="space-y-4">
            <AnimatePresence mode="popLayout">
              {items.map((item, index) => (
                <motion.div
                  key={item.id}
                  layout
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, scale: 0.95 }}
                  className="bg-white rounded-2xl p-4 shadow-sm border border-gray-100 flex items-center gap-4 group"
                >
                  <div className="w-12 h-12 bg-gray-50 rounded-xl flex items-center justify-center text-gray-500">
                    {item.type === "image" ? <ImageIcon className="w-6 h-6" /> : <FileText className="w-6 h-6" />}
                  </div>
                  
                  <div className="flex-1 min-w-0">
                    <h4 className="font-semibold text-gray-900 truncate">{item.name}</h4>
                    <p className="text-xs text-gray-500 uppercase font-bold tracking-widest mt-0.5">{item.type}</p>
                  </div>

                  <div className="flex items-center gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button 
                      onClick={() => handleAIProcess(item.id)}
                      disabled={item.aiProcessing}
                      className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition-colors flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider"
                    >
                      {item.aiProcessing ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Sparkles className="w-3.5 h-3.5" />}
                      AI Magic
                    </button>
                    <button 
                      onClick={() => removeItem(item.id)}
                      className="p-2 text-red-500 hover:bg-red-50 rounded-lg transition-colors"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                </motion.div>
              ))}
            </AnimatePresence>

            {items.length === 0 && (
              <div className="text-center py-12 text-gray-400 italic">
                No content added yet. Start by uploading some files.
              </div>
            )}
          </div>
        </div>
      </main>

      {/* URL Modal */}
      <AnimatePresence>
        {showUrlModal && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[100] bg-black/60 backdrop-blur-sm flex items-center justify-center p-4"
          >
            <motion.div 
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="bg-white w-full max-w-md rounded-3xl p-8 shadow-2xl"
            >
              <h2 className="text-xl font-bold mb-4">Add Web Content</h2>
              <p className="text-sm text-gray-500 mb-6">Enter a URL and AI will extract the key information for your PDF.</p>
              
              <input 
                type="url" 
                value={urlInput}
                onChange={(e) => setUrlInput(e.target.value)}
                placeholder="https://example.com"
                className="w-full px-4 py-3 bg-gray-50 border-none rounded-2xl focus:ring-2 focus:ring-blue-500 outline-none mb-6"
              />

              <div className="flex gap-3">
                <button 
                  onClick={() => setShowUrlModal(false)}
                  className="flex-1 px-6 py-3 rounded-2xl font-medium text-gray-600 hover:bg-gray-100 transition-colors"
                >
                  Cancel
                </button>
                <button 
                  onClick={addUrlContent}
                  disabled={isFetchingUrl || !urlInput}
                  className="flex-1 px-6 py-3 bg-blue-600 text-white rounded-2xl font-medium hover:bg-blue-700 disabled:opacity-50 flex items-center justify-center gap-2"
                >
                  {isFetchingUrl ? <Loader2 className="w-4 h-4 animate-spin" /> : <Plus className="w-4 h-4" />}
                  Add Content
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Preview Modal */}
      <AnimatePresence>
        {showPreview && previewUrl && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[100] bg-black/60 backdrop-blur-sm flex items-center justify-center p-4 lg:p-12"
          >
            <motion.div 
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="bg-white w-full max-w-5xl h-full rounded-[2.5rem] overflow-hidden flex flex-col shadow-2xl"
            >
              <div className="px-8 py-6 border-b border-gray-100 flex items-center justify-between bg-white">
                <div>
                  <h2 className="text-xl font-bold text-gray-900">PDF Preview</h2>
                  <p className="text-sm text-gray-500">{options.title}.pdf</p>
                </div>
                <div className="flex items-center gap-3">
                  <button 
                    onClick={() => setShowPreview(false)}
                    className="px-6 py-2.5 rounded-full font-medium text-gray-600 hover:bg-gray-100 transition-colors"
                  >
                    Close
                  </button>
                  <button 
                    onClick={downloadPDF}
                    className="flex items-center gap-2 px-6 py-2.5 bg-blue-600 text-white rounded-full font-medium hover:bg-blue-700 shadow-lg shadow-blue-200 transition-all active:scale-95"
                  >
                    <Download className="w-4 h-4" />
                    Download PDF
                  </button>
                </div>
              </div>
              
              <div className="flex-1 bg-gray-100 p-8 overflow-auto flex justify-center">
                <iframe 
                  src={previewUrl} 
                  className="w-full max-w-4xl h-full bg-white shadow-xl rounded-lg border-none"
                  title="PDF Preview"
                />
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
